/// Flutter icons HomeMenuIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HomeMenuIcons
///      fonts:
///       - asset: fonts/HomeMenuIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HomeMenuIcons {
  HomeMenuIcons._();

  static const _kFontFam = 'HomeMenuIcons';
  static const String? _kFontPkg = null;

  static const IconData favorites = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorites_outlined = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sheets = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lists = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
